### ISSUE TITLE
`circular import` in task pool

### ISSUE THREAD

**Issue by superstar54** [aiidateam/aiida-workgraph#342]
As originally planned, we want to allow the developer to define their `task` or `workgroup` at the entry points.

```
[project.entry-points."aiida_workgraph.task"]
"workgraph_collections.qe.pdos" = "workgraph_collections.qe.pdos:pdos_workgraph"
```

After the adding the entry point, I ran:
```
from aiida_workgraph import WorkGraph, task

```

This gave an error:

```
$ python test_pdos.py 
Traceback (most recent call last):
  File "/home/wang_x3/tests/entry_points/test_pdos.py", line 1, in <module>
    from aiida_workgraph import WorkGraph, task
  File "/home/wang_x3/repos/superstar54/aiida-workgraph/aiida_workgraph/__init__.py", line 8, in <module>
    from .workgraph import WorkGraph
  File "/home/wang_x3/repos/superstar54/aiida-workgraph/aiida_workgraph/workgraph.py", line 23, in <module>
    class WorkGraph(node_graph.NodeGraph):
  File "/home/wang_x3/repos/superstar54/aiida-workgraph/aiida_workgraph/workgraph.py", line 36, in WorkGraph
    from aiida_workgraph.tasks import task_pool
  File "/home/wang_x3/repos/superstar54/aiida-workgraph/aiida_workgraph/tasks/__init__.py", line 5, in <module>
    **get_entries(entry_point_name="aiida_workgraph.task"),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wang_x3/apps/miniforge3/envs/aiida/lib/python3.11/site-packages/node_graph/utils.py", line 16, in get_entries
    entry = entry_point.load()
            ^^^^^^^^^^^^^^^^^^
  File "/home/wang_x3/apps/miniforge3/envs/aiida/lib/python3.11/importlib/metadata/__init__.py", line 198, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wang_x3/apps/miniforge3/envs/aiida/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wang_x3/repos/superstar54/workgraph-collections/workgraph_collections/qe/pdos.py", line 5, in <module>
    from aiida_workgraph import WorkGraph
ImportError: cannot import name 'WorkGraph' from partially initialized module 'aiida_workgraph' (most likely due to a circular import) (/home/wang_x3/repos/superstar54/aiida-workgraph/aiida_workgraph/__init__.py)
```

**Comment by GeigerJ2** [comment]
Hi @superstar54, OK if I work on this?

**Comment by superstar54** [comment]
Hi @GeigerJ2 , thanks for looking at this issue. For the moment, I don't have an good solution to fix it. You can have a quick try, but if there is no solution either, then we go to the worst case: drop out the `node-graph` package and rewrite it inside the `aiida-workgraph` directly; if it is this case, it will be huge of work, so I will probably work on it.

**Comment by GeigerJ2** [comment]
Alright, thanks for the quick response! Just had a quick look at the repo this morning, as I'll be working on WorkGraph during the coding days, so feel free to assign me to any issues that you think are more suitable than this one (there are already a few for the v0.5 release that I assigned myself to). I'll have a look at this issue still, merging `node-graph` into `aiida-workgraph` seems like excessive effort.
